<a href="https://colab.research.google.com/github/ucfilho/optim_raianars_Insight_out_of_date/blob/master/DE_OPTIM_ANN_012_Insight.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import time
import matplotlib.pyplot as plt
import numpy as np
from random import randint
from scipy import optimize
import pandas as pd

In [0]:
def AvaliaX(X):
  nrow,ncol=X.shape
  fitness = np.asarray([Fun(ind) for ind in X])
  best_idx = np.argmin(fitness)
  best = X[best_idx]
  fobj_best = fitness[best_idx]
  y=fitness
  BEST=best
  FOBEST=fobj_best
  XY= np.c_[X,y] #concatena x e y em 2 colunas            
  XYsorted = XY[XY[:,-1].argsort()] #Ordena a partir da last col(Y) for all row
  x=XYsorted[:,0:ncol]
  XY=XYsorted
  BEST_XY =np.append(BEST,FOBEST)
  return XY,BEST_XY,BEST,FOBEST

In [0]:
# Functions
def sigmoid(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

def tasig(x,deriv=False):
    if(deriv==True):
        return 1-x*x
    return 2/(1+np.exp(-2*x))-1

# purelin function
def purelin(x,deriv=False):
    if(deriv==True):
        return 1
    return x

In [0]:
# funcao normatiza dados
def Normatiza(x_train,X_max,X_min):
    strings=list(x_train)
    k=-1
    for i in strings:
        k=k+1
        max_x=X_max[k]
        min_x=X_min[k]
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x_train[i]=(x_train[i]-a)/b
    return x_train

In [0]:
def GetMatriz(ANN):
  nrow0=int(ANN.iloc[0,1]);#print(nrow0);
  ncol0=int(ANN.iloc[1,1]);#print(ncol0);
  nrow1=int(ANN.iloc[2,1]);#print(nrow1);
  ncol1=int(ANN.iloc[3,1]);#print(ncol1);
  Col=np.array(range(2,ncol0+2)); # print(Col)
  Row=np.array(range(0,nrow0)); # print(Row)
  syn0=np.array(ANN.iloc[Row,Col])
  syn0=pd.DataFrame(syn0).dropna() 
  syn0=np.array(syn0)
  ncol=int(ANN.iloc[0,1])
  syn1=ANN.iloc[:,(ncol0+ncol1+1)] ;#print(syn1_F)
  nrow=len(np.array(syn1.dropna()))
  A=np.zeros((nrow,1));
  A[:,0]=np.copy(syn1.dropna());
  syn1=np.copy(A);#print(pd.DataFrame(syn1_F))
  X_max=np.array(ANN.iloc[:,ncol-1].dropna());#print(X_max_F)
  X_min=np.array(ANN.iloc[:,ncol-2].dropna());#print(X_min_F)

  return syn0,syn1,X_max,X_min

In [0]:
# funcao retorna os dados a forma original
def Original(x_train,X_max,X_min):
    strings=list(x)
    k=-1
    for i in strings:
        k=k+1
        max_x=X_max[k]
        min_x=X_min[k]
        a=(max_x+min_x)/2
        b=(max_x-min_x)/2
        x_train[i]=x_train[i]*b+a
    return x_train

In [0]:
def ANN_ycal(syn0,syn1,X_train):
  l0 = X_train
  l1 = tasig(np.dot(l0,syn0))
  l2 = purelin(np.dot(l1,syn1))
  y_calc=np.reshape(l2,len(l2))
  return y_calc

In [0]:
def Classifica(ycalc):
  n=len(ycalc)
  for i in range(n):
    if(ycalc[i]<0):
      ycalc[i]=-1
    else:
      ycalc[i]=1
  return ycalc

In [0]:
!git clone https://github.com/ucfilho/ANN_read_matrix #clonar do Github
%cd ANN_read_matrix

fatal: destination path 'ANN_read_matrix' already exists and is not an empty directory.
/content/ANN_read_matrix


In [0]:
ANN_F=pd.read_csv('ANN_INSIGHT_Valor_F.csv')

In [0]:

nrow0=int(ANN_F.iloc[0,1]);#print(nrow0);
ncol0=int(ANN_F.iloc[1,1]);#print(ncol0);
nrow1=int(ANN_F.iloc[2,1]);#print(nrow1);
ncol1=int(ANN_F.iloc[3,1]);#print(ncol1);
Col=np.array(range(2,ncol0+2)); # print(Col)
Row=np.array(range(0,nrow0)); # print(Row)
syn0_F=np.array(ANN_F.iloc[Row,Col])
syn0_F=pd.DataFrame(syn0_F).dropna() 
syn0_F=np.array(syn0_F)
ncol=int(ANN_F.iloc[0,1])
syn1_F=ANN_F.iloc[:,(ncol0+ncol1+1)];#print(syn1_F)
nrow=len(np.array(syn1_F.dropna()))
A=np.zeros((nrow,1));
A[:,0]=np.copy(syn1_F.dropna());
syn1_F=np.copy(A);#print(pd.DataFrame(syn1_F))
X_max_F=np.array(ANN_F.iloc[:,ncol-1].dropna());#print(X_max_F)
X_min_F=np.array(ANN_F.iloc[:,ncol-2].dropna());#print(X_min_F)


In [0]:
print(X_max_F);print(X_min_F);print(pd.DataFrame(syn0_F));print(syn1_F);

[-1.38985534  0.50011348 -0.92687391  0.26286818]
[-2.37319103 -4.33770547  1.40522909 -1.93761416]
          0         1         2  ...         6         7         8
0 -2.373191 -1.389855  3.361735  ... -1.352513 -0.349394  3.926464
1 -4.337705  0.500113  1.815637  ... -4.192328 -0.158768  2.785641
2  1.405229 -0.926874  4.668511  ...  1.519539 -5.504849  2.816117
3 -1.937614  0.262868 -0.327463  ... -1.589595 -1.142875 -0.737920

[4 rows x 9 columns]
[[-1.89271281]
 [ 3.49053673]
 [ 5.3437096 ]
 [ 1.95434157]
 [ 3.57743608]
 [ 2.09473036]
 [ 2.15157938]
 [ 2.60760389]
 [-2.94261576]]


In [0]:
syn0_FF,syn1_FF,X_max_FF,X_min_FF=GetMatriz(ANN_F)

In [0]:
print(X_max_FF);print(X_min_FF);print(pd.DataFrame(syn0_FF));print(syn1_FF);

[-1.38985534  0.50011348 -0.92687391  0.26286818]
[-2.37319103 -4.33770547  1.40522909 -1.93761416]
          0         1         2  ...         6         7         8
0 -2.373191 -1.389855  3.361735  ... -1.352513 -0.349394  3.926464
1 -4.337705  0.500113  1.815637  ... -4.192328 -0.158768  2.785641
2  1.405229 -0.926874  4.668511  ...  1.519539 -5.504849  2.816117
3 -1.937614  0.262868 -0.327463  ... -1.589595 -1.142875 -0.737920

[4 rows x 9 columns]
[[-1.89271281]
 [ 3.49053673]
 [ 5.3437096 ]
 [ 1.95434157]
 [ 3.57743608]
 [ 2.09473036]
 [ 2.15157938]
 [ 2.60760389]
 [-2.94261576]]


In [0]:
ANN_CR=pd.read_csv('ANN_INSIGHT_CR.csv')

In [0]:
############################### Importar códigos
!git clone https://github.com/ucfilho/optim_raianars_Insight/ #clonar do Github
%cd optim_raianars_Insight
import de_soma_Insight
import de_bounds_matriz

In [0]:
############################### DADOS DE ENTRADA 
RUNS=1 #NÚMERO DE RODADAS
#mut=0.8
#crossp=0.7
  ############################### Função
import Function

'''
Fun=Function.Rosenbrock
dim=30
MAX=np.repeat(10,dim)
MIN=np.repeat(-10,dim)

  #Global optimum: f(xi)= 0
'''
'''
dim=30
Fun=Function.Sphere
MAX=np.repeat(5.12,dim)
MIN=np.repeat(-5.12,dim)
  # f(x)=0 x=(0,0) [-5.12,5.12]
'''
#'''
dim=2
Fun=Function.Schwefel
MAX=np.repeat(500,dim)
MIN=np.repeat(-500,dim)
  #Global optimum: f(xi)= 0 for xi = 420.968746 for i=1,...,n  ;  xi in [-500,500]  
#'''
'''
dim=30
Fun=Function.Rastrigin
MAX=np.repeat(5.12,dim)
MIN=np.repeat(-5.12,dim)
  # f(x)=0 x=(0,0) [-5.12,5.12]
'''
'''
dim=30
Fun=Function.Sum_of_different_powers
MAX=np.repeat(1,dim)
MIN=np.repeat(-1,dim)
  # f(x)=0 x=(0,0)
'''
'''  
dim=30
Fun=Function.Ackley
MAX=np.repeat(32,dim)
MIN=np.repeat(-32,dim)
 # f(x)=0 x=(0,0) [-32, 32]
'''
'''  
dim=30
Fun=Function.Michalewicz
MAX=np.repeat(np.pi,dim)
MIN=np.repeat(0,dim)
 #fx=-9.66015 p/ d=10 [0,pi]
'''
'''  
dim=30
Fun=Function.
MAX=np.repeat(1,dim)
MIN=np.repeat(-1,dim)
'''

PAR=len(MAX) #NUM DE PARAMETROS A SER OTIMIZADOS


In [0]:
def GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL):
  global fields
  global syn0_F,syn1_F,X_max_F,X_min_F
  global syn0_CR,syn1_CR,X_max_CR,X_min_CR
  nrow,ncol=X.shape
  FOBESTm=1e99
  Fo=MAT_INDo[0,6]    # VALOR Fo   
  CRo=MAT_INDo[0,7]   # VALOR CRo
  QUANT=17 # quantos indices esta fazendo
  MAT_IND=np.zeros((1,QUANT))

  REF=0.1 # REFERENCIA DE DIFERENCAS ENTRE OS ELEMENTOS
  
  XY,BEST_XY,BEST,FOBEST=AvaliaX(X)
  soma=0
  for j in range(ncol):
    for i in range(nrow):
        Xj=np.mean(X[:,j])
        soma=soma+(X[i,j]-Xj)**2
  DI=(soma/nrow)**0.5
  DIr=DI/DIo
  MAT_IND[0,0]=DI #dispersao
  MAT_IND[0,1]=DIr # dispersao relativa
  MAT_IND[0,2]=SOMA/TOTAL # fracao relativa

  V1=FOBESTo
  V2=FOBEST
  A=2*V2
  if(V1 > A):
    MAT_IND[0,3]=2 # o valor de fobj torna pelo menos duas vezes melhor
  elif (V2==V1):
    MAT_IND[0,3]=0 # o valor de fobj nao altera
  else:
    MAT_IND[0,3]=1 # o valor de fobj melhora mas menos que duas vezes
  
  # MAT_IND[0,4]  # VELOC X
  DELTA=np.amax(abs(BEST-BESTo))
  if( DELTA >REF):
    MAT_IND[0,4]=2 # difere  for i in range(1,len(PARTIC)):
  elif ( DELTA == 0):
    MAT_IND[0,4]=0 # sem diferenca entre as posicoes do xbest entre duas buscas
  else:
    MAT_IND[0,4]=1 # diferenca entre as posicoes  do xbest menor que ref
  
  MAT_IND[0,5]=nrow  # VALOR NP
  nrow,ncol=XY.shape
  MAT_IND[0,8]=XY[0,(ncol-1)] # VALOR fmin
  MAT_IND[0,9]=XY[(nrow-1),(ncol-1)] # VALOR fmax
  # MAT_IND[0,10] # Valor AD_fmin 
  if abs(MAT_IND[0,8]/MAT_IND[0,8])>1:
    MAT_IND[0,10]=1/abs(MAT_IND[0,8])
  else:
    MAT_IND[0,10]=MAT_IND[0,8]/MAT_IND[0,8]
  # MAT_IND[0,11] # Valor AD_fmax
  if abs(MAT_IND[0,9]/MAT_IND[0,9])>1: # tem que pegar primeira
    MAT_IND[0,11]=1/abs(MAT_IND[0,9]) # tem que pegar primeira
  else:
    MAT_IND[0,11]=MAT_IND[0,9]/MAT_IND[0,9] # tem que pegar do anterior

  # MAT_IND[0,12] # DELTA Fobj
  MAT_IND[0,12]=MAT_IND[0,3]-MAT_IND[0,3]  # tem que pegar do anterior
  

  # MAT_IND[0,13] # DELTA Vx
  MAT_IND[0,13]=MAT_IND[0,4]-MAT_IND[0,4]  # tem que pegar do anterior

  # MAT_IND[0,14] # r_fitness
  Fmin=0.05
  if (MAT_IND[0,8]==0):
    MAT_IND[0,14]=Fmin
  elif (MAT_IND[0,9]==0):
    MAT_IND[0,14]=Fmin
  else:
    if abs(MAT_IND[0,9]/MAT_IND[0,8])<1:
      MAT_IND[0,14]=1-abs(MAT_IND[0,9]/MAT_IND[0,8])
    else:
      MAT_IND[0,14]=1-abs(MAT_IND[0,8]/MAT_IND[0,9])

  MAT_IND[0,6]=Fo
  MAT_IND[0,7]=CRo

  # comecando a rede!!!
  #['DI RELATIVO', 'FRAC Its', 'Fo', 'CRo'] VALORES A USAR
  #MAT_IND[0,1]=DIr # dispersao relativa
  #MAT_IND[0,2]=SOMA/TOTAL # fracao relativa
  #MAT_IND[0,6]=Fo
  #MAT_IND[0,7]=CRo
  
  x_train=MAT_INDo[0,[1,2,6,7]]
  x_train=pd.DataFrame(x_train).T

  nrow,ncol=ANN_F.shape
  x_train=Normatiza(x_train,X_max_F,X_min_F)
  y_calc=ANN_ycal(syn0_F,syn1_F,x_train)
  y_quali=Classifica(y_calc)
  Fo=Fo+0.5
  CRo=CRo+2
  
  MAT_IND[0,15]=Fo # valor de F que sai da rede
  MAT_IND[0,16]=CRo # valor de CR que sai da rede

  
  return MAT_IND



In [0]:
fields = ['DI RELATIVO','FRAC Its','Fo','CRo']




In [0]:
##################################### IMPORTAR MÓDULOS

NMAX=1000 # maximo tamanho da populacao

dimensions=len(MAX)

start_time = time.time() #INICIALIZA CONTAGEM DO TEMPO
its=1 #10 # quantas vezes vai usar o NPAR antes de alterar de novo
ITE=6 #10 # PONTOS quantas vezes vai alteral NPAR 
#PARTIC=[10,80,10,400,100,100,100,100,100,100]
#ITE=50 # so para testar

#TOTAL=7*dim*its*ITE
TOTAL=10*dim*its*ITE

maxiter=3
popsize=5
p=int(TOTAL/its/ITE) 
NPAR=p

MAX_P=np.zeros(ITE) # ATENCAO para variar F e Cr MAX_P passa a ser 3 vezes maior
MIN_P=np.zeros(ITE) # ATENCAO para variar F e Cr MIN_P passa a ser 3 vezes maior

for i in range(dim):
  MAX_P[i]=MAX[i] 
  MIN_P[i]=MIN[i]


for i in range(RUNS):
  SOMA=0
  pop = np.random.rand(NPAR, dimensions)
  diff=np.zeros(PAR)
  for ii in range(PAR):
    diff[ii] = MAX[ii]-MIN[ii]
  X = MIN + pop * diff
    
  PONTOS=ITE # DIVISOES DA POPULACAO
 
 ############################################################
  #bounds=[(5*dim, 15*dim)] * PONTOS # ITE
  #bounds=[(3*dim, 12*dim)] * PONTOS # ITE
  #bounds=[(4*dim, 16*dim)] * PONTOS
  
  # nao pode ser assim pq o bounds vale p o DE nao dos parametros
  #p=int(TOTAL/its/ITE) 
  bounds=[(p, p)] * PONTOS
  #bounds=[]
  #for k in range(dim):
  #  bounds.append((MIN[k], MAX[k]))
  # print("=========bounds=",bounds)
    


  '''
  #Geral
  new_mut=(0,1)
  new_crossp=(0,1)
  '''
  #'''
  #Multimodal Separável 
  new_mut=(0.5,1)
  new_crossp=(0,0.5)
  #'''
  '''
  #Multimodal Não Separável 
  new_mut=(0.5,1)
  new_crossp=(0.5,1)
  '''
  '''
  ##### Unimodal Separável
  new_mut=(0,0.5)
  new_crossp=(0,0.5)
  '''
  '''
  ##### Unimodal Não Separável
  new_mut=(0,0.5)
  new_crossp=(0.5,1)
  '''
 ############################################################ 
  # nao pode ser assim pq o bounds vale p o DE nao dos parametros
  ''' '''
  for j in range(PONTOS):
    bounds.append(new_mut)
    
  for j in range(PONTOS):
    bounds.append(new_crossp)

  DIo=1e99
  mut=0.5;crossp=0.5;
  CRo=crossp;Fo=mut;
  #Xo=np.copy(X)
  XY,BEST_XY,BESTo,FOBESTo=AvaliaX(X)
  nrow,ncol=X.shape

  QUANT=17;MAT_INDo=np.zeros((1,QUANT)); # quantos indices esta fazendo
  MAT_INDo[0,5]=nrow  # VALOR NP
  MAT_INDo[0,6]=Fo    # VALOR Fo   
  MAT_INDo[0,7]=CRo   # VALOR CRo
  
  MAT_INDo=GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL)
  
  DIo=np.copy(MAT_INDo[0,0])
  pd.set_option('display.max_columns', 30)  
  MAT_INDo[0,15]=Fo    # VALOR Fo   
  MAT_INDo[0,16]=CRo   # VALOR CRo
  MAT=[]
  for loop in range(ITE):
    X,BEST,FOBEST,XY,BEST_XY,SOMA= de_soma_Insight.de(MAX,MIN, mut, crossp,NPAR,
                                                      its,Fun,X,SOMA,TOTAL)
    
    MAT_IND=GeraIndices(X,BESTo,FOBESTo,DIo,MAT_INDo,SOMA,TOTAL)
    
    BESTo=np.copy(BEST);FOBESTo=np.copy(FOBEST);
    MAT.append(MAT_IND.ravel())
    
    MAT_INDo[0,6]=MAT_IND[0,15]   # VALOR Fo   
    MAT_INDo[0,7]=MAT_IND[0,16]   # VALOR CRo
    
NOMES=['DIVERSIDADE (DI)',  'DI RELATIVO','FRAC Its',
           'VELOC FOBJ','VELOC X','NP','Fo','CRo','fmin','fmax',
           'AD_fmin','AD_fmax','DELTA FOBJ','DELTA VX','r_fitness',
           'F','CR']
df  = pd.DataFrame(MAT, columns=NOMES)
pd.set_option('display.max_columns', 30)
pd.set_option('display.max_rows', 30)
print(df)